// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqWbeBDD5n6dvbYI0AW_h-rIYJsH0cdpg',
    appId: '1:302553443829:web:e810601f46fffb4e1c04bc',
    messagingSenderId: '302553443829',
    projectId: 'consolida-app',
    authDomain: 'consolida-app.firebaseapp.com',
    storageBucket: 'consolida-app.firebasestorage.app',
    measurementId: 'G-KY3XVQLXQ9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqWbeBDD5n6dvbYI0AW_h-rIYJsH0cdpg',
    appId: '1:302553443829:web:6b3abda4711b43461c04bc',
    messagingSenderId: '302553443829',
    projectId: 'consolida-app',
    authDomain: 'consolida-app.firebaseapp.com',
    storageBucket: 'consolida-app.firebasestorage.app',
    measurementId: 'G-VJQTY3F1F2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHLXLC3u-BqSl-jq7QzItp6ij9M19X0k',
    appId: '1:302553443829:ios:f614c6d4c725d8db1c04bc',
    messagingSenderId: '302553443829',
    projectId: 'consolida-app',
    storageBucket: 'consolida-app.firebasestorage.app',
    iosBundleId: 'com.example.tfgApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHLXLC3u-BqSl-jq7QzItp6ij9M19X0k',
    appId: '1:302553443829:ios:f614c6d4c725d8db1c04bc',
    messagingSenderId: '302553443829',
    projectId: 'consolida-app',
    storageBucket: 'consolida-app.firebasestorage.app',
    iosBundleId: 'com.example.tfgApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYKw8PvusgTv_nt6KZoQiGtzr5zbYMS_0',
    appId: '1:302553443829:android:7cde8219f01220921c04bc',
    messagingSenderId: '302553443829',
    projectId: 'consolida-app',
    storageBucket: 'consolida-app.firebasestorage.app',
  );

}